Neuroevolution: Exercise 1 
=========
###### Artur Ganzha 10019651
---------	
###### Raul Gorek 10061333
---------	

In [421]:
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt

## Aufgabe 1

In [422]:
# Datensatz
X = np.array([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
y = np.array([0.0, 1.0, 1.0, 0.0]) 

In [423]:
def xor(a, b):
    return (a or b) and not (a and b)


In [424]:
def relu(x):
    return x * (x > 0)

In [425]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

## Aufgabe 2

In [426]:
class NeuralNetwork:
    def __init__(self, layers: list):
        self.layers = layers
        for layer in self.layers:
            layer.init()

    def forward_pass(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x
    
class Linear:
    def __init__(self, input_size, output_size, activation = relu):
        self.input_size = input_size
        self.output_size = output_size
        self.activation = activation
    
    def init(self):
        self.W = np.random.uniform(-1, 1,(self.input_size,self.output_size))
    
    def forward(self, x):
        self.in_pass = x
        self.fw = np.dot(self.in_pass, self.W)
        self.act_forward = self.activation(self.fw)
        return self.act_forward




In [427]:
layers = [
    Linear(2,8),
    Linear(8, 4),
    Linear(4,1, sigmoid)
]

In [428]:
neural_net = NeuralNetwork(layers)

In [429]:
batch = np.array([[0,0],[0,1]])
neural_net.forward_pass(batch)

array([[0.5       ],
       [0.63509017]])

## Aufgabe 3

In [430]:
def binary_cross_entropy_loss(prediction, ground_truth):
    return -(ground_truth * np.log(prediction) + (1-ground_truth) * np.log(1-prediction))

In [431]:
def derivative_bcel(prediction, ground_truth):
    x =  np.where(ground_truth == 0, 1.0 / (1.0 - prediction), -1.0 / prediction)
    return x

In [432]:
def derivative_relu(z):
    return np.where(z >=0, 1.0, 0.0)

In [433]:
def derivative_sigmoid(z):
    x = sigmoid(z)
    return x * (1-x)

# Aufgabe 4

In [434]:
def backward_pass(self, deriv_loss, learn_rate, prediction, ground_truth):
    deriv = deriv_loss(prediction, ground_truth)
    for layer in reversed(self.layers):
        if layer.activation == relu:
            self.deriv_act = np.multiply(deriv, derivative_relu(layer.fw))
        elif layer.activation == sigmoid:
            self.deriv_act = derivative_sigmoid(layer.fw)
        deriv = np.dot(self.deriv_act, layer.W.T)
        update_deriv = np.dot(layer.in_pass.T, self.deriv_act)
        layer.W -= learn_rate * update_deriv



In [435]:
NeuralNetwork.backward_pass = backward_pass

In [436]:
num_epochs = 100
batch = np.array([[0,0],[0,1], [1,0], [1,1]])
labels = np.array([[0.0], [1.0], [1.0], [0.0]]) 
for i in range(num_epochs):
    y_hat = neural_net.forward_pass(batch)
    neural_net.backward_pass(derivative_bcel, 0.01, y_hat, labels)
    loss = binary_cross_entropy_loss(y_hat, labels)
    print("Loss: ", loss)
print(neural_net.forward_pass(batch))

Loss:  [[0.69314718]
 [0.45398829]
 [0.43714813]
 [1.09953957]]
Loss:  [[0.69314718]
 [0.45756251]
 [0.44121532]
 [1.0883204 ]]
Loss:  [[0.69314718]
 [0.46109549]
 [0.44524486]
 [1.07737021]]
Loss:  [[0.69314718]
 [0.46458682]
 [0.44923594]
 [1.06668347]]
Loss:  [[0.69314718]
 [0.46803613]
 [0.45318786]
 [1.0562546 ]]
Loss:  [[0.69314718]
 [0.47144314]
 [0.45709996]
 [1.04607802]]
Loss:  [[0.69314718]
 [0.47480762]
 [0.46097165]
 [1.03614816]]
Loss:  [[0.69314718]
 [0.47812938]
 [0.46480242]
 [1.02645945]]
Loss:  [[0.69314718]
 [0.48140829]
 [0.4685918 ]
 [1.01700633]]
Loss:  [[0.69314718]
 [0.48464425]
 [0.4723394 ]
 [1.00778329]]
Loss:  [[0.69314718]
 [0.48783725]
 [0.47604489]
 [0.99878485]]
Loss:  [[0.69314718]
 [0.49098727]
 [0.47970799]
 [0.99000558]]
Loss:  [[0.69314718]
 [0.49409437]
 [0.48332846]
 [0.98144011]]
Loss:  [[0.69314718]
 [0.49715864]
 [0.48690615]
 [0.97308311]]
Loss:  [[0.69314718]
 [0.5001802 ]
 [0.49044093]
 [0.96492934]]
Loss:  [[0.69314718]
 [0.50315921]
 [0.4

## Aufgabe 5

In [442]:
def train(NeuralNetwork: NeuralNetwork, learn_rate, batch_size, num_epochs, labels):
    losses = []
    accuracies = []

    for i in tqdm(range(num_epochs), desc="Training"):
        y_hat = neural_net.forward_pass(batch_size)
        loss = binary_cross_entropy_loss(y_hat, labels)
        neural_net.backward_pass(derivative_bcel, learn_rate, y_hat, labels)
        losses.append(loss)
        
        predictions = (y_hat >= 0.5).astype(float)
        accuracy = np.mean(predictions == labels)
        accuracies.append(accuracy)

    return losses, accuracies

In [444]:
epochs_tqdm = 1000
batch_tqdm = np.array([[0,0],[0,1], [1,0], [1,1]])
labels_tqdm = np.array([[0.0], [1.0], [1.0], [0.0]]) 
train(neural_net, 0.001, batch_tqdm, epochs_tqdm, labels_tqdm)

Training: 100%|██████████| 1000/1000 [00:00<00:00, 22712.80it/s]


([array([[0.69314718],
         [0.65369161],
         [0.68433213],
         [0.69314718]]),
  array([[0.69314718],
         [0.65374132],
         [0.68440406],
         [0.69314718]]),
  array([[0.69314718],
         [0.65379101],
         [0.68447597],
         [0.69314718]]),
  array([[0.69314718],
         [0.65384066],
         [0.68454786],
         [0.69314718]]),
  array([[0.69314718],
         [0.65389028],
         [0.68461972],
         [0.69314718]]),
  array([[0.69314718],
         [0.65393988],
         [0.68469156],
         [0.69314718]]),
  array([[0.69314718],
         [0.65398944],
         [0.68476338],
         [0.69314718]]),
  array([[0.69314718],
         [0.65403897],
         [0.68483517],
         [0.69314718]]),
  array([[0.69314718],
         [0.65408848],
         [0.68490694],
         [0.69314718]]),
  array([[0.69314718],
         [0.65413795],
         [0.68497869],
         [0.69314718]]),
  array([[0.69314718],
         [0.65418739],
         [0.68