Neuroevolution: Exercise 1 
=========
###### Artur Ganzha 10019651
---------	
###### Raul Gorek 10061333
---------	

In [445]:
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt

## Aufgabe 1

In [446]:
# Datensatz
X = np.array([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
y = np.array([0.0, 1.0, 1.0, 0.0]) 

In [447]:
def xor(a, b):
    return (a or b) and not (a and b)


In [448]:
def relu(x):
    return x * (x > 0)

In [449]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

## Aufgabe 2

In [450]:
class NeuralNetwork:
    def __init__(self, layers: list):
        self.layers = layers
        for layer in self.layers:
            layer.init()

    def forward_pass(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x
    
class Linear:
    def __init__(self, input_size, output_size, activation = relu):
        self.input_size = input_size
        self.output_size = output_size
        self.activation = activation
    
    def init(self):
        self.W = np.random.uniform(-1, 1,(self.input_size,self.output_size))
    
    def forward(self, x):
        self.in_pass = x
        self.fw = np.dot(self.in_pass, self.W)
        self.act_forward = self.activation(self.fw)
        return self.act_forward




In [451]:
layers = [
    Linear(2,8),
    Linear(8, 4),
    Linear(4,1, sigmoid)
]

In [452]:
neural_net = NeuralNetwork(layers)

In [453]:
batch = np.array([[0,0],[0,1]])
neural_net.forward_pass(batch)

array([[0.5       ],
       [0.29010198]])

## Aufgabe 3

In [454]:
def binary_cross_entropy_loss(prediction, ground_truth):
    return -(ground_truth * np.log(prediction) + (1-ground_truth) * np.log(1-prediction))

In [455]:
def derivative_bcel(prediction, ground_truth):
    x =  np.where(ground_truth == 0, 1.0 / (1.0 - prediction), -1.0 / prediction)
    return x

In [456]:
def derivative_relu(z):
    return np.where(z >=0, 1.0, 0.0)

In [457]:
def derivative_sigmoid(z):
    x = sigmoid(z)
    return x * (1-x)

# Aufgabe 4

In [458]:
def backward_pass(self, deriv_loss, learn_rate, prediction, ground_truth):
    deriv = deriv_loss(prediction, ground_truth)
    for layer in reversed(self.layers):
        if layer.activation == relu:
            self.deriv_act = np.multiply(deriv, derivative_relu(layer.fw))
        elif layer.activation == sigmoid:
            self.deriv_act = derivative_sigmoid(layer.fw)
        deriv = np.dot(self.deriv_act, layer.W.T)
        update_deriv = np.dot(layer.in_pass.T, self.deriv_act)
        layer.W -= learn_rate * update_deriv



In [459]:
NeuralNetwork.backward_pass = backward_pass

In [460]:
num_epochs = 100
batch = np.array([[0,0],[0,1], [1,0], [1,1]])
labels = np.array([[0.0], [1.0], [1.0], [0.0]]) 
for i in range(num_epochs):
    y_hat = neural_net.forward_pass(batch)
    neural_net.backward_pass(derivative_bcel, 0.01, y_hat, labels)
    loss = binary_cross_entropy_loss(y_hat, labels)
    print("Loss: ", loss)
print(neural_net.forward_pass(batch))

Loss:  [[0.69314718]
 [1.23752278]
 [1.01922393]
 [0.25471243]]
Loss:  [[0.69314718]
 [1.25402491]
 [1.02752469]
 [0.24785944]]
Loss:  [[0.69314718]
 [1.27069968]
 [1.03597938]
 [0.24112219]]
Loss:  [[0.69314718]
 [1.28754336]
 [1.04458773]
 [0.23450266]]
Loss:  [[0.69314718]
 [1.30455188]
 [1.05334934]
 [0.22800272]]
Loss:  [[0.69314718]
 [1.32172088]
 [1.06226361]
 [0.22162406]]
Loss:  [[0.69314718]
 [1.3390457 ]
 [1.07132983]
 [0.2153682 ]]
Loss:  [[0.69314718]
 [1.35652141]
 [1.08054711]
 [0.2092365 ]]
Loss:  [[0.69314718]
 [1.37414281]
 [1.0899144 ]
 [0.20323011]]
Loss:  [[0.69314718]
 [1.39190448]
 [1.09943052]
 [0.19735   ]]
Loss:  [[0.69314718]
 [1.40980074]
 [1.10909412]
 [0.19159694]]
Loss:  [[0.69314718]
 [1.42782574]
 [1.11890371]
 [0.18597149]]
Loss:  [[0.69314718]
 [1.44597339]
 [1.12885767]
 [0.18047405]]
Loss:  [[0.69314718]
 [1.46423749]
 [1.13895422]
 [0.17510477]]
Loss:  [[0.69314718]
 [1.48261166]
 [1.14919148]
 [0.16986363]]
Loss:  [[0.69314718]
 [1.5010894 ]
 [1.1

## Aufgabe 5

In [470]:
def train(neural_net: NeuralNetwork, learn_rate, batch_size, num_epochs, labels):
    losses = []
    accuracies = []

    for i in tqdm(range(num_epochs), desc="Training"):
        y_hat = neural_net.forward_pass(batch_size)
        loss = binary_cross_entropy_loss(y_hat, labels)
        neural_net.backward_pass(derivative_bcel, learn_rate, y_hat, labels)
        losses.append(loss)
        

        predictions = (y_hat >= 0.5).astype(float)
        accuracy = np.mean(predictions == labels)
        accuracies.append(accuracy)
    print("Acc:", accuracies)
    return losses, accuracies

In [471]:
epochs_tqdm = 1000
batch_tqdm = np.array([[0,0],[0,1], [1,0], [1,1]])
labels_tqdm = np.array([[0.0], [1.0], [1.0], [0.0]]) 
train(neural_net, 0.001, batch_tqdm, epochs_tqdm, labels_tqdm)

Training: 100%|██████████| 1000/1000 [00:00<00:00, 21564.32it/s]

Acc: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25

([array([[6.93147181e-01],
         [6.59142649e+00],
         [6.29518133e+00],
         [2.17381093e-05]]),
  array([[6.93147181e-01],
         [6.59150891e+00],
         [6.29527353e+00],
         [2.17349250e-05]]),
  array([[6.93147181e-01],
         [6.59159132e+00],
         [6.29536573e+00],
         [2.17317414e-05]]),
  array([[6.93147181e-01],
         [6.59167373e+00],
         [6.29545793e+00],
         [2.17285584e-05]]),
  array([[6.93147181e-01],
         [6.59175613e+00],
         [6.29555011e+00],
         [2.17253762e-05]]),
  array([[6.93147181e-01],
         [6.59183853e+00],
         [6.29564229e+00],
         [2.17221946e-05]]),
  array([[6.93147181e-01],
         [6.59192092e+00],
         [6.29573447e+00],
         [2.17190138e-05]]),
  array([[6.93147181e-01],
         [6.59200330e+00],
         [6.29582663e+00],
         [2.17158336e-05]]),
  array([[6.93147181e-01],
         [6.59208568e+00],
         [6.29591879e+00],
         [2.17126541e-05]]),
  array([[